name: Server CD

on:
  push:
    branches:
      - main
    paths:
      - hossi-server/**

env:
  SERVICE_NAME: hossi
  PORT: ${{ secrets.PORT }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/hossi:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        working-directory: hossi-server
        run: |
          docker build \
            -f src/main/docker/Dockerfile.multistage \
            -t $IMAGE \
            --build-arg GCP_PROJECT_ID=${GCP_PROJECT_ID} \
            .
      - name: Push the docker image to Container Registry
        run: docker push $IMAGE
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --project $GCP_PROJECT_ID \
            --region $GCP_REGION \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=GCP_PROJECT_ID=${GCP_PROJECT_ID} \
            --quiet

  notice_success:
    if: success()
    needs: [deploy]

    runs-on: ubuntu-latest

    steps:
      - name: Success CI
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "${{ github.workflow }} 成功したよ:eyes:"
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }} success",
                "title_link": "${{ github.event.pull_request._links.html.href }}",
                "footer": "timestamp: ${{ github.event.pull_request.updated_at }}"
              }
            ]

  notice_failure:
    if: failure()
    needs: [deploy]

    runs-on: ubuntu-latest

    steps:
      - name: Failure CI
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "<!channel> ${{ github.workflow }} 失敗したよ:eyes:"
          attachments: |
            [
              {
                "color": "danger",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }} failure",
                "title_link": "${{ github.event.pull_request._links.html.href }}",
                "footer": "timestamp: ${{ github.event.pull_request.updated_at }}"
              }
            ]
