name: Front CI

on:
  push:
    branches:
      - main
    paths:
      - hossi-front/**
  pull_request:
    branches:
      - main
    paths:
      - hossi-front/**

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.16.1"
      - run: yarn
        working-directory: hossi-front
      - run: yarn lint
        working-directory: hossi-front
      - run: yarn build
        working-directory: hossi-front

  notice_success:
    if: success()
    needs: [ci]

    runs-on: ubuntu-latest

    steps:
      - name: Success CI
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "${{ github.workflow }} 成功したよ:eyes:"
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }} success",
                "title_link": "${{ github.event.pull_request._links.html.href }}",
                "footer": "timestamp: ${{ github.event.pull_request.updated_at }}"
              }
            ]

  notice_failure:
    if: failure()
    needs: [ci]

    runs-on: ubuntu-latest

    steps:
      - name: Failure CI
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: "<!channel> ${{ github.workflow }} 失敗したよ:eyes:"
          attachments: |
            [
              {
                "color": "danger",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "title": "PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }} failure",
                "title_link": "${{ github.event.pull_request._links.html.href }}",
                "footer": "timestamp: ${{ github.event.pull_request.updated_at }}"
              }
            ]
