name: Server CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Test
      working-directory: hossi-server
      run: ./mvnw test

  check_style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-review'
        workdir: hossi-server
        filter_mode: nofilter
        # level: error

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Graalvm
      id: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.0.0.2'
        java: 'java11'
    - name: build
      working-directory: hossi-server
      run: ./mvnw package -Pnative

  notice_success:
    if: success()
    needs: [test, check_style, build]

    runs-on: ubuntu-latest

    steps:
    - name: Success CI
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: "${{ github.workflow }} 成功したよ:eyes:"
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "title": "PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }} success",
              "title_link": "${{ github.event.pull_request._links.html.href }}",
              "footer": "timestamp: ${{ github.event.pull_request.updated_at }}"
            }
          ]

  notice_failure:
    if: failure()
    needs: [test, check_style, build]

    runs-on: ubuntu-latest

    steps:
    - name: Failure CI
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: "<!channel> ${{ github.workflow }} 失敗したよ:eyes:"
        attachments: |
          [
            {
              "color": "danger",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "title": "PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }} failure",
              "title_link": "${{ github.event.pull_request._links.html.href }}",
              "footer": "timestamp: ${{ github.event.pull_request.updated_at }}"
            }
          ]
